sig/engine:
  - "cmd/*"
  - "components/backup/*"
  - "components/collections/*"
  - "components/engine_*/*"
  - "components/error_code/src/engine.rs"
  - "components/error_code/src/lib.rs"
  - "components/error_code/src/raftstore.rs"
  - "components/error_code/src/sst_importer.rs"
  - "components/error_code/src/storage.rs"
  - "components/error_code/src/bin.rs"
  - "components/external_storage/*"
  - "components/file_system/*"
  - "components/keys/*"
  - "components/raft_log_engine/*"
  - "components/raftstore/*"
  - "components/rusoto_util/*"
  - "components/sst_importer/*"
  - "components/test_raftstore/*"
  - "components/test_sst_importer/*"
  - "components/test_storage/*"
  - "components/tikv_util/*"
  - "etc/*"
  - "metrics/*"
  - "src/import/*"
  - "src/server/*"
  - "src/storage/*"
  - "src/config.rs"
  - "src/lib.rs"
  - "src/read_pool.rs"

sig/raft:
  - "components/batch-system/*"
  - "components/cdc/*"
  - "components/configuration/*"
  - "components/encryption/*"
  - "components/error_code/src/encryption.rs"
  - "components/error_code/src/raft.rs"
  - "components/error_code/src/pd.rs"
  - "components/into_other/*"
  - "components/resolved_ts/*"
  - "components/security/*"
  - "components/test_pd/*"
  - "components/test_util/*"
  - "components/tests/*"

sig/coprocessor:
  - "components/codec/*"
  - "components/error_code/src/codec.rs"
  - "components/error_code/src/coprocessor.rs"
  - "components/log_wrappers/*"
  - "components/match_template/*"
  - "components/panic_hook/*"
  - "components/profiler/*"
  - "components/test_coprocessor/*"
  - "components/tidb_query_*/*"
  - "components/tikv_alloc/*"
  - "components/tipb_helper/*"
  - "src/coprocessor/*"

sig/transaction:
  - "components/concurrency_manager/*"
  - "components/txn_types/*"

sig/scheduling:
  - "components/pd_client/*"

